server.port=8080

spring.datasource.url=jdbc:mysql://127.0.0.1:3307/bitacora?useUnicode=true&characterEncoding=utf8&serverTimezone=Europe/Madrid
spring.datasource.username=usuario
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
app.jwt.secret=TorremolinosMalag@321canelaYmilo
app.jwt.issuer=bitacora-universal
app.jwt.ttl-seconds=604800